# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Math.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nMath.proto\x12\x05shade\"\"\n\ncommandadd\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0bresponseadd\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"\x1a\n\x07\x63ommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x1c\n\x08response\x12\x10\n\x08response\x18\x01 \x01(\t2\xc0\x01\n\x04Math\x12,\n\x03\x61\x64\x64\x12\x11.shade.commandadd\x1a\x12.shade.responseadd\x12+\n\x04\x63hat\x12\x0e.shade.command\x1a\x0f.shade.response(\x01\x30\x01\x12\x30\n\x05\x63ount\x12\x11.shade.commandadd\x1a\x12.shade.responseadd0\x01\x12+\n\x06recite\x12\x0e.shade.command\x1a\x0f.shade.response(\x01\x62\x06proto3')



_COMMANDADD = DESCRIPTOR.message_types_by_name['commandadd']
_RESPONSEADD = DESCRIPTOR.message_types_by_name['responseadd']
_COMMAND = DESCRIPTOR.message_types_by_name['command']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
commandadd = _reflection.GeneratedProtocolMessageType('commandadd', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDADD,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:shade.commandadd)
  })
_sym_db.RegisterMessage(commandadd)

responseadd = _reflection.GeneratedProtocolMessageType('responseadd', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEADD,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:shade.responseadd)
  })
_sym_db.RegisterMessage(responseadd)

command = _reflection.GeneratedProtocolMessageType('command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:shade.command)
  })
_sym_db.RegisterMessage(command)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:shade.response)
  })
_sym_db.RegisterMessage(response)

_MATH = DESCRIPTOR.services_by_name['Math']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDADD._serialized_start=21
  _COMMANDADD._serialized_end=55
  _RESPONSEADD._serialized_start=57
  _RESPONSEADD._serialized_end=83
  _COMMAND._serialized_start=85
  _COMMAND._serialized_end=111
  _RESPONSE._serialized_start=113
  _RESPONSE._serialized_end=141
  _MATH._serialized_start=144
  _MATH._serialized_end=336
# @@protoc_insertion_point(module_scope)
